### ISSUE TITLE
IndexError on /flashcards/practice/

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/proso-apps#155]
From outlinemaps.org:

```
[2016-03-31 19:31:29,509] ERROR "Internal Server Error: /flashcards/practice/"
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/lazysignup/decorators.py", line 47, in wrapped
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_flashcards/views.py", line 380, in practice
    items_in_queue=len(load_query_json(request.GET, "avoid", "[]")))
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_flashcards/models.py", line 203, in practice
    test_flashcard = flashcards.pop(test_position)
IndexError: pop from empty list
```

**Comment by papousek** [comment]
The last occurrence is from 2016-04-05, so closing.
