### ISSUE TITLE
Empty option sets on /models/practice/

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/proso-apps#157]
From outlinemaps.org:

```
[2016-05-31 19:44:57,198] ERROR "Internal Server Error: /models/practice/"
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/lazysignup/decorators.py", line 47, in wrapped
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_models/views.py", line 305, in practice
    return render_json(request, result, template='models_json.html', help_text=practice.__doc__)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/response.py", line 51, in render_json
    json = enrich_json_objects_by_object_type(request, json)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/enrichment.py", line 101, in enrich_json_objects_by_object_type
    enricher_info['enricher'](request, enricher_objects, enricher_nested)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/enrichment.py", line 118, in enricher_fun
    return _enricher_fun(enricher)(request, json_list, nested)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_flashcards/json_enrich.py", line 44, in options
    allow_zero_options=allow_zero_option
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/models/option_selection.py", line 47, in select_options_more_items
    number_of_options = self.options_number().get_number_of_options(target_probability, prediction, allow_zero_options[item], len(item_options))
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/models/option_selection.py", line 80, in get_number_of_options
    raise Exception("Zero options are not allowed, but there are no candidates for options in case of item.")
Exception: Zero options are not allowed, but there are no candidates for options in case of item.
```

**Comment by papousek** [comment]
Fixed in geography by this commit c9d3359cc3434362f5e19cdb478bff105ae87870.
