### ISSUE TITLE
KeyError: 'options' on /models/practice/

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/proso-apps#158]
From outlinemaps.org:

```
[2016-05-31 15:23:45,094] ERROR "Internal Server Error: /models/practice/"
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/lazysignup/decorators.py", line 47, in wrapped
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_models/views.py", line 305, in practice
    return render_json(request, result, template='models_json.html', help_text=practice.__doc__)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/response.py", line 51, in render_json
    json = enrich_json_objects_by_object_type(request, json)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/enrichment.py", line 101, in enrich_json_objects_by_object_type
    enricher_info['enricher'](request, enricher_objects, enricher_nested)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso/django/enrichment.py", line 118, in enricher_fun
    return _enricher_fun(enricher)(request, json_list, nested)
  File "/usr/local/share/.virtualenvs/outlinemaps-production-2/lib/python3.5/site-packages/proso_flashcards/json_enrich.py", line 58, in options
    question['payload']['options'] = sorted(question['payload']['options'], key=lambda o: o['term']['name'])
KeyError: 'options'
```

**Comment by papousek** [comment]
Caused by this: https://github.com/adaptive-learning/geography/issues/160
