### ISSUE TITLE
load_flashcards fails on staging.anatom.cz

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#174]
I run
```
(anatomy3-staging)[slaweet@adaprive-learning anatomy-staging]$ ./source/manage.py load_flashcards /var/www/webs/anatomytagging/source/anatomy-flashcards.json --skip-language-check
```

and it ended with
```
Filling item types

Building dependencies
[################################] 2941/2941 - 00:00:00
[2016-08-09 08:22:06,664] DEBUG "loaded function result ({1: {'language': 'lang', 'valid': True, 'foreign_key': 'item_id', 'object_type': 'item_type', 'model': 'proso_tasks.models.Task', 'table': 'proso_tasks_task', 'id': 1}, 2: {'language': 'lang', 'valid': True, 'foreign_key': 'item_id', 'object_type': 'item_type', 'model': 'proso_tasks.models.Context',...) form CACHE; key: get_all_types:args:[<class 'proso_models.models.ItemTypeManager'>]-kwargs:{}..., hash ae2bf62086525ed59c045aaadc60506c31385953"
Traceback (most recent call last):
  File "./source/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso_flashcards/management/commands/load_flashcards.py", line 55, in handle
    self._load_flashcards(data["flashcards"], options['ignored_flashcards'])
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso_flashcards/management/commands/load_flashcards.py", line 257, in _load_flashcards
    self._load_item_relations(data, db_flashcards, 'categories')
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso_flashcards/management/commands/load_flashcards.py", line 287, in _load_item_relations
    flatten(parent_subgraph.values()), lang
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso_models/models.py", line 729, in translate_identifiers
    for item_type_id, type_identifiers in proso.list.group_by(identifiers, by=lambda identifier: self.get_item_type_id_from_identifier(identifier, item_types)).items():
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso/list.py", line 46, in group_by
    return proso.dict.group_keys_by_values({x: by(x) for x in what})
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso/list.py", line 46, in <dictcomp>
    return proso.dict.group_keys_by_values({x: by(x) for x in what})
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso_models/models.py", line 729, in <lambda>
    for item_type_id, type_identifiers in proso.list.group_by(identifiers, by=lambda identifier: self.get_item_type_id_from_identifier(identifier, item_types)).items():
  File "/usr/local/share/.virtualenvs/anatomy3-staging/lib/python3.5/site-packages/proso_models/models.py", line 770, in get_item_type_id_from_identifier
    raise Exception('There is no item type for name "{}".'.format(identifier_type))
Exception: There is no item type for name "proso_flashcards_term".
```

**Comment by papousek** [comment]
To uz tu bylo. Vzpominam si, ze tobe loadovani nefungovalo a me nejakou zahadou ano.

**Comment by papousek** [comment]
Solved by unsetting PROSO_ON_PRODUCTION in postactivate file on production server and separating memcached instance from matmat.
