### ISSUE TITLE
bug from anatom.cz

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/proso-apps#77]
```
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/lazysignup/decorators.py", line 45, in wrapped
    return func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/proso_flashcards/views.py", line 336, in practice
    items_in_queue=len(load_query_json(request.GET, "avoid", "[]")))
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/proso_flashcards/models.py", line 175, in practice
    with_contexts)
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/proso_flashcards/models.py", line 235, in _load_options
    allow_zero_options=allow_zero_option)
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/proso/models/option_selection.py", line 62, in select_options_more_items
    allow_zero_options=allow_zero_options[item], **kwargs) for item in items]
  File "/usr/local/share/.virtualenvs/anatomy/lib/python2.7/site-packages/proso/models/option_selection.py", line 105, in select_options
    raise Exception('There are no options for multiple-choice question! Number of options set to: {}, confusing factors {}'.format(number_of_options, confusing_items))
Exception: There are no options for multiple-choice question! Number of options set to: 1, confusing factors []
```

**Comment by slaweet** [comment]
There are contexts with just one flashcard in given category, e.g. for 1 General anatomy:
cary-lidskeho-tela-1svg: {number_of_flashcards: 1
casti-kosterniho-svalu-obecnesvg: {number_of_flashcards: 1
