### ISSUE TITLE
Update to proso-apps==1.2.13 fails on my Ubuntu machine

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#93]
The error is the following:

```
$ pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): dj-database-url==0.3.0 in /home/xstanis1/.virtualenvs/anatomy/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting proso-apps==1.2.13 (from -r requirements.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/download.py", line 857, in _download_http_url
    stream=True,
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 36, in send
    cached_response = self.controller.cached_request(request)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 102, in cached_request
    resp = self.serializer.loads(request, self.cache.get(cache_url))
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 108, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 170, in _loads_v2
    cached["response"]["body"]
  File "/home/xstanis1/.virtualenvs/anatomy/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 20, in _b64_decode_bytes
    return base64.b64decode(b.encode("ascii"))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0133' in position 10650061: ordinal not in range(128)

```
However, it works on my Fedora machine

**Comment by papousek** [comment]
wow?

**Comment by slaweet** [comment]
And today it just worked.
